"""
All of the EDW meta data links came from https://data.fs.usda.gov/geodata/edw/datasets.php 
which is the FSGeodata Clearinghouse.  The page has a feature class table.  Each row in the table 
describes the geospatial feature class and provides a link to the metadatda (xml links in the EDW array) 
and a link to the ArcGIS map service.  The metadata xml linkx are CSDGM.
"""
EDW = [
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_RngVegImprove.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_SilvTSI.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_SilvReforestation.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_HazFuelTrt_LN.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_HazFuelTrt_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_TimberHarvest.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_MBHR_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_CFLRP_LN.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_CFLRP_PT.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_CFLRP_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_IRR_LN.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_IRR_PT.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_IRR_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_StwrdshpCntrctng_LN.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_StwrdshpCntrctng_PT.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_StwrdshpCntrctng_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_WBBS_LN.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_WBBS_PT.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_WBBS_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_KnutsonVandenberg.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Activity_BrushDisposal.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.AdministrativeForest.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.AdministrativeRegion.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RangerDistrict.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EcoMapProvinces.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PNV_KuchlerSections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PNV_2000Sections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.SoilsSections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EcomapSections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ClimateSections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.NationalLandcoverSections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.FennemanJohnsonPhySections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PNV_KuchlerSubsections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PNV_2000Subsections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.SoilsSubsections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EcomapSubsections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ClimateSubsections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.NationalLandcoverSubsections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.FennemanJohnsonPhySubsections.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.HealthyForestRestoration.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.HealthyForestRestoration_2015.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.HealthyForestRestoration_2016.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.HealthyForestRestoration_2017.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.HealthyForestRestoration_2018.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.HealthyForestRestoration_2019.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.HealthyForestRestoration_2020.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.HealthyForestRestoration_2021.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.CFLR_HPRP_ProjectBoundary.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.InvasivePlantCurrent.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.DevelopedSite.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ALPGeopoliticalUnit.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.CERCLASITE.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.LMPU.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.LandUtilizationProject.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.MINERALRIGHT.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.OtherNationalDesignatedArea.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.OthNatlDesgAreaStatus.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.NFSLandUnit.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.NationalGrassland.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.WildScenicRiver_LN.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.WildScenicRiverSegment_LN.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.WildScenicRiver.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Wilderness.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ProclaimedForest.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ProclaimedForest_Grassland.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.OtherSubSurfaceRight.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.OtherSurfaceRight.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Withdrawal.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Corner.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Monument.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.QuarterSection.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Section.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Township.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PurchaseUnit.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RightOfWay.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.SpecialInterestManagementArea.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.SpecialStatusArea.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.BasicOwnership.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.SurfaceOwnership.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.SMABoundary.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Tract.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.WildScenicRiverStatus.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.WildernessStatus.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PADUS_Fee.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PADUS_Designation.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PADUS_Proc.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.PADUS_Easement.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Allotment.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Pasture.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.WildHorseBurro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RECAREAACTIVITIES_V.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Rec_RecreationSitesINFRA.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RECREATIONOPPORTUNITIES.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RoadlessArea_2001.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RoadlessArea_2001_ID_CO.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RoadlessArea_CO_2012.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RoadlessArea_ID_2008.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Road_MVUM.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Trail_MVUM.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.RoadCore_FS.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.TrailNFS_Publish.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.WatershedConditionClass.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Periodical_Cicada_Brood.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.AerialFireRetardantAvoidance.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R01.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R10.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R02.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R03.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R04.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R05.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R06.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R08.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_R09.AFRAA_Hydro.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Bio_AquaticOrgPassage_Act_ext.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Bio_AquaticOrgPassage_HbMi_ext.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Bio_AquaticOrgPassage_Survey.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.BdyPln_BIL_LandscpInvestment.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EV_CalvegZones_Ecoregions.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ClimateShield_BULL0BRK0_1980.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ClimateShield_BULL0BRK0_2040.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ClimateShield_BULL0BRK0_2080.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ClimateShield_CT0BRK0_1980.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ClimateShield_CT0BRK0_2040.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ClimateShield_CT0BRK0_2080.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Util_CommSite_SpeclUse.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Ecosys_TEUI_Status.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_CentralCoast.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_CentralValley.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_GreatBasin.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_NorCoastEast.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_NorCoastMid.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_NorCoastWest.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_NorthInterior.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_NorthSierra.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_SouCoast.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_SouthInterior.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.EVMid_R05_SouthSierra.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Experimental_Area_Boundaries.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Experimental_Area_Locations.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region01.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region02.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region03.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region04.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region05.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region06.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region08.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region09.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/Actv_CommonAttribute_PL_Region10.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Lndcv_FIA_CntyEst_2015_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Lndcv_FIA_CntyEst_2016_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Lndcv_FIA_CntyEst_2017_PL.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Fire_Occurrence_FIRESTAT_YRLY.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Actv_ProjectArea_FSNRC.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Fire_FireshedReg_Fireshed.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Fire_FireshedReg_ProjArea.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.FSCommonNames.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Com_TimberAppraisalZone_RDs.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Com_TimberAppraisalZone.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Bdyown_LWCF_Parcel.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Bld_FS_Office_Location.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_Pct_StreamFlow_NFS.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Infra_GAOA_Project_Detail_LN.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Infra_GAOA_Project_Detail_PT.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Infra_NAMP_Partner_Agreement.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Infra_GAOA_Project_Summary.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_FurthestHead.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_Heads.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_LongestStream.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_MtnRanges.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_PourPoint.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_Regions.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_Streams4000.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_ValleyBottom.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_GrBasin_Watersheds.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Historical_Woodlands_1873.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_FlowMet_2080sChgAbs.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_FlowMet_2040sChgAbs.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_FlowMet_2080s.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_FlowMet_1990s.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_FlowMet_2040s.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_FlowMet_2080sChgPct.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Hydro_FlowMet_2040sChgPct.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.BdyDesg_Land_FASAB.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.MTBS_BURN_AREA_BOUNDARY.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.MTBS_FIRE_OCCURRENCE_PT.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Actv_ProjectArea_NEPA.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.FirePerimeterFinal.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.FireOccurrence.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.FirePerimeter.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.NorWeST_TemperaturePoints.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.NorWeST_PredictedStreams.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.BdyOwn_PILT_ASR.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Fire_RAVG_Perimeters_PostfireVegChg.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Fire_RAVG_Perimeters_PostfireVegChg_ByForest.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ResearchStationBoundaries.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ResearchStationBoundaries_Gen.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ResearchStationFacilities.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Actv_ProjectArea_SAIPlan.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Fire_FPA_FOD_6th_Fires.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.ForestsToFaucets.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.FORESTSONTHEEDGE.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Actv_ProjectArea_TimberSale.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Tongass_Landslide_Areas.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Tongass_Landslide_Initiation.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.TRIBALCEDEDLANDS.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.TribalCededLandsTable.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Actv_SilvReforestation_Needs.xml",
    "https://data.fs.usda.gov/geodata/edw/edw_resources/meta/S_USA.Actv_SilvTSI_Needs.xml",
]

"""
Source for CRV MapService urls: https://apps.fs.usda.gov/fsgisx05/rest/services/wo_nfs_gtac
"""
CRV = [
    "https://apps.fs.usda.gov/fsgisx05/rest/services/wo_nfs_gtac/EDW_ForestSystemBoundaries_01/MapServer?f=pjson",
    "https://apps.fs.usda.gov/fsgisx02/rest/services/wo_nfs_gstc/WO_OSC_GapAnalysis_Climate/MapServer?f=pjson",
    "https://services1.arcgis.com/gGHDlz6USftL5Pau/arcgis/rest/services/Firesheds_with_NFS_Lands_in_the_West_view/FeatureServer/0?f=pjson",
    "https://apps.fs.usda.gov/fsgisx02/rest/services/wo_nfs_gstc/WO_OSC_GapAnalysis_OldGrowthAndMatureForests/MapServer?f=pjson",
    "https://apps.fs.usda.gov/arcx/rest/services/wo_nrm_iweb/NRM_WCATTWatershedCondAssess/MapServer?f=pjson",
]

# data_dot_gov_urls = [
#     "https://catalog.data.gov/harvest/object/203bed83-5da3-4a64-b156-ea016f277b07",
#     "https://catalog.data.gov/harvest/object/04643a90-e5fd-4602-a8fa-e8195dd16c5e",
#     "https://catalog.data.gov/harvest/object/abf916ec-6ddd-4030-8f5e-3b317a33ba1e",
#     "https://catalog.data.gov/harvest/object/589436ca-1324-4773-9201-acecd5d83448",
#     "https://catalog.data.gov/harvest/object/21392fa4-ff86-4ac8-9f38-33d67aef770c",
#     "https://catalog.data.gov/harvest/object/9216c0ce-d083-48a6-b017-e0efc0fada37",
#     "https://catalog.data.gov/harvest/object/0b20b4e4-34f8-4d1d-ae1c-7a405d0f6d36",
#     "https://catalog.data.gov/harvest/object/36b9144a-dc24-43cf-85c3-49a08dbed762",
#     "https://catalog.data.gov/harvest/object/9d60be08-5c3b-45a7-8ae6-017a4ca9433c",
#     "https://catalog.data.gov/harvest/object/a4a75240-4fac-40f7-a327-6596becff636",
#     "https://catalog.data.gov/harvest/object/8df82322-0812-46c7-b2b3-52829a8417e1",
#     "https://catalog.data.gov/harvest/object/0419db56-01a4-4a97-a4f0-1fb903e77cdf",
#     "https://catalog.data.gov/harvest/object/32d5b113-e83c-48f3-b05a-fd99ed7a3a92",
#     "https://catalog.data.gov/harvest/object/f2e66a1c-10b6-4243-920a-0b64352b8c63",
#     "https://catalog.data.gov/harvest/object/a0a63e30-b3cb-418b-8616-d89ee2e9e100",
# ]

