# Generated by Django 5.1.1 on 2024-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_added_catalog_search_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Domain name (required)', max_length=250, unique=True)),
                ('description', models.CharField(help_text='Domain name description (optional)', max_length=500, null=True)),
                ('root_domain', models.CharField(choices=[('usfs', 'United States Forest Service')], default='usfs')),
                ('host_system_name', models.CharField(blank=True, help_text='System name currently hosting the data (i.e. Redshift,  Oracle)', max_length=500, null=True)),
                ('host_system_type', models.CharField(blank=True, help_text='System type currently hosting the data', max_length=500, null=True)),
                ('format', models.CharField(choices=[('TABULAR', 'Tabular'), ('TABULAR_AND_GEOSPATIAL', 'Tabular and Geospatial'), ('GEOSPATIAL', 'Geospatial'), ('N/A', 'N/A')], help_text='The data format', max_length=125, null=True)),
            ],
            options={
                'db_table': 'domains',
            },
        ),
    ]
